//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bastille.Id.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bastille.Id.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Event Handler: Using token endpoint &quot;{0}&quot;..
        /// </summary>
        internal static string DebugCookieTokenEndpointUsedMessageText {
            get {
                return ResourceManager.GetString("DebugCookieTokenEndpointUsedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Event Handler: Invalid Signout Backchannel Token!.
        /// </summary>
        internal static string DebugCookieTokenInvalidMessageText {
            get {
                return ResourceManager.GetString("DebugCookieTokenInvalidMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Event Handler: An exception error occurred during an attempt to refresh the user&apos;s access token..
        /// </summary>
        internal static string DebugCookieTokenRefreshExceptionErrorText {
            get {
                return ResourceManager.GetString("DebugCookieTokenRefreshExceptionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Event Handler: Access Token Refresh Gently Failed. The following reasons were reported below.
        ///Error: {0}
        ///Description: {1}
        ///Type: {2}
        ///Http Error Reason: {3}
        ///.
        /// </summary>
        internal static string DebugCookieTokenRefreshFailedMessageText {
            get {
                return ResourceManager.GetString("DebugCookieTokenRefreshFailedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Event Handler: Access Token Expired. Attempting Refresh..
        /// </summary>
        internal static string DebugCookieTokenRefreshProcessMessageText {
            get {
                return ResourceManager.GetString("DebugCookieTokenRefreshProcessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Event Handler: Access Token Refresh Successful.
        ///access_token: {0}
        ///refresh_token: {1}..
        /// </summary>
        internal static string DebugCookieTokenRefreshSuccessMessageText {
            get {
                return ResourceManager.GetString("DebugCookieTokenRefreshSuccessMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Event Handler: Checking Cookie Token is Valid.
        /// </summary>
        internal static string DebugCookieTokenValidateProcessCheckMessageText {
            get {
                return ResourceManager.GetString("DebugCookieTokenValidateProcessCheckMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookie Event Handler: The user cookie token was validated successfully and has not expired..
        /// </summary>
        internal static string DebugCookieTokenValidTokenMessageText {
            get {
                return ResourceManager.GetString("DebugCookieTokenValidTokenMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIDC Message: 
        ///    {0}.
        /// </summary>
        internal static string DebugOpenIdMessageRecievedMessageText {
            get {
                return ResourceManager.GetString("DebugOpenIdMessageRecievedMessageText", resourceCulture);
            }
        }
    }
}
